spring.application.name=exam_wallet-api 
server.port=8080
# MongoDB
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=badwallet

# Logging
logging.level.com.badwallet=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
